### PR TITLE
feat(dropdown): add autoClose support

### LINKED ISSUE #169: dropdown: more features implemented
Hello,

I have taken the liberty to further implement the dropdown component:
- it uses same attributes as uib-dropdown: "is-open", "auto-close"
- auto-close implemented for "always", "clickOutside", "other_string" (=disabled)
- Always listens to keyboard: impl ESC to close and Enter to toggle
- fixed setting some bs4 css classes

See this plunk: http://plnkr.co/edit/bpM2AW?p=preview

Deviating from what you already had, all 3 selectors are attributes (like uib before), not elements. I hope, I have not violated the spirit of ng2, esp. in the case where global event listeners are involved.

Please let me know if you find this useful, I can provide a PR then.

Best wishes, dmdm

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Fixes #169 

This PR adds API docs as well.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Should then close on a click anywhere?

**Comment by pkozlowski-opensource** [comment]
> Should then close on a click anywhere?

Actually - why not! Just pushed an update.

**Comment by Foxandxss** [comment]
I asked because I didn't see any test for that.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss see updated tests + code

**Comment by Foxandxss** [comment]
LGTM

**Pull request closed without merging**
