### PR TITLE
feat(tabset): add disable option to tabset

### PR DESCRIPTION
**Pull request by sendilkumarn**
#214

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
It is a good beginning, but I think that disabled tabs are getting particular CSS classes, no?

**Comment by sendilkumarn** [comment]
disabled class to list item ?

**Comment by pkozlowski-opensource** [comment]
`<a class="nav-link disabled">Disabled</a>`, see example here: http://v4-alpha.getbootstrap.com/components/navs/#tabs

Obviously we also need a test that shows that a tab gets proper CSS classes in response to changes in the disabled state.

**Comment by sendilkumarn** [comment]
is it okay to add that in all methods.. wherever `expectactivetabs` is present?

**Comment by sendilkumarn** [comment]
@pkozlowski-opensource  let me know if anything else to be added here

**Pull request closed without merging**
