### PR TITLE
feat(dropdown): emit open state upstream

### PR DESCRIPTION
**Pull request by wesleycho**
- Emit open state changes upstream so users can react to changes

### CODE REVIEW

**Comment by Foxandxss** [comment]
Were is my docs and tests? :P

**Comment by pkozlowski-opensource** [comment]
You've forgotten to commit:
* [ ] - tests
* [ ] - API doc update

**Comment by pkozlowski-opensource** [comment]
Sammit, Fox was 3 ms faster :-)

**Comment by Foxandxss** [comment]
You need one more monitor.

**Comment by pkozlowski-opensource** [comment]
LGTM

**Comment by pkozlowski-opensource** [comment]
Merging

**Pull request closed without merging**
