### PR TITLE
feat(NgbModalBackdrop): add NgbModalBackdrop needed for Modal support

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This one should be fairly easy to review :-)

### CODE REVIEW

**Comment by wesleycho** [comment]
LGTM for an initial start - we'll probably want to implement backdrop clicking logic later for dismissing the modal, but that can come later.

**Comment by pkozlowski-opensource** [comment]
> Oh, I see the backdrop logic is in the modal window

Exactly - if I understand things correctly the HTML structure is different in B4.

**Comment by Foxandxss** [comment]
Do we need a component for something without template?

**Comment by pkozlowski-opensource** [comment]
> Do we need a component for something without template?

We can't dynamically load directives, so pretty much yes.... I'm sure that there are alternative designs so I'm open to other suggestions.

**Comment by Foxandxss** [comment]
Didn't know about that limitation. Good for me then.

**Pull request closed without merging**
