### PR TITLE
chore: update folder organization and file naming

### LINKED ISSUE #64: Folder organization and file naming
Could we discuss a slightly different organization of our folders? My main motivation here is to have files that change together go together. In this spirit I would propose (an example for one component):

```
src
    rating
        rating.ts        
        rating.spec.ts
    core.ts
```

How does it sound?

### PR DESCRIPTION
**Pull request by Foxandxss**
I updated the folder structure and file naming as suggested by @pkozlowski-opensource 

The system.config part is a bit brittle, but I hope that this entire workaround goes away anytime soon.

Fixes #64

### CODE REVIEW

**Comment by Foxandxss** [comment]
Wop, clang doing its awesome indentation. Let me fix that.

**Comment by Foxandxss** [comment]
Fixed.

**Comment by pkozlowski-opensource** [comment]
LGTM!

**Comment by Foxandxss** [comment]
@pkozlowski-opensource You know what that means right?



And where it says commits, means PRs.

**Pull request closed without merging**
