### PR TITLE
docs: accordion demo

### PR DESCRIPTION
**Pull request by Foxandxss**
Werk in progress.

I need to tidy up the code and stuff like that (the templates is another subject).

This setup will allow multiple demos per component (to show different features).

I tried to extract as much as possible in the json so in the future we can make this more generic.

Also notice how I imported the accordion in the demo (@ng-bootstrap/accordion) which is how we are going to use it in prod, so better to show in the demo that way. This alias won't work twice, so I will need to make changes on the core itself so each component is exported. We will probably need something like that for the scoped packages. I will think about this.

Probably a few things are horrible, but I am asleeeep.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Ah, I managed the alias thing so every package can be imported in that way for the docs without the need of touching the codebase.

**Comment by icfantv** [comment]
For the path thing we saw Sunday?  Nice.

**Comment by wesleycho** [comment]
LGTM

**Comment by icfantv** [comment]
LGTM.

**Pull request closed without merging**
