### PR TITLE
chore(demo): demo site tweaks

### PR DESCRIPTION
**Pull request by icfantv**
Before submitting a pull request, please make sure you have at least performed the following:

* replaced `Loading...` with something more stylish
* increased spacing between directive and description

### CODE REVIEW

**Comment by wesleycho** [comment]
How does this fare in IE?

**Comment by icfantv** [comment]
I have no idea - I can't test it as I don't have access to windows.  I'm assuming you mean the `<style>` tag in the `<body>`?

**Comment by pkozlowski-opensource** [comment]
My understanding from the yesterday's meeting is that we are not going to land this one so closing for now. Please re-open if there are parts that should land.

**Comment by icfantv** [comment]
@pkozlowski-opensource confirming w/ @Foxandxss - we had a discussion after the meeting and I was of the impression that this was ok.  Will confirm.

**Comment by icfantv** [comment]
reopening per Slack comments.

**Pull request closed without merging**
