### PR TITLE
fix(demo): add cursor pointer for code icon

### PR DESCRIPTION
**Pull request by sirajc**
Fixes: Pointer stays as arrow when we hover over code icon in Example wrapper

### CODE REVIEW

**Comment by icfantv** [comment]
@pkozlowski-opensource, @Foxandxss: I'm reading [this document](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role) and it's sounding like we should make this an `<input type="image" role="button"/>`.  The latter attribute will give us both ARIA compliance and the pointer cursor because BS4 has a `[role="button"]` selector.  Thoughts?

**Comment by wesleycho** [comment]
Wouldn't wrapping it in an anchor tag and using that as the click target accomplish the purpose as well?

**Comment by sirajc** [comment]
@wesleycho Wrapping it in anchor shows cursor, but then we need to add `href="#"` and hovering shows the address. Also we need to add a style on a, because it renders `underlined` on hover
Since this is not a link and actually an action, IMO this should be a button

@icfantv just adding `role="button"` on `img` is also working great, Have updated PR
@wesleycho your thougts?

**Comment by wesleycho** [comment]
No, you don't need to add `href="#"`, just `href`.

**Pull request closed without merging**
