### PR TITLE
WIP: chore(docs): add API docs extraction script

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This is WIP (see the details of the remaining work below) but it already does quite a lot and properly extracts info from all the existing directives.

You can see usage example in `get-doc.js` (this file will go away in the final PR).

@icfantv you can pull to generate example docs
all: we can start documenting directives done so far (JSDoc on classes / inputs / outputs)

### CODE REVIEW

**Comment by Foxandxss** [comment]
If it is ready, please merge, I will make use of it.

**Comment by pkozlowski-opensource** [comment]
Remarks so far:
* [ ] sort inputs and outputs alphabetically 
* [ ] return (top level) should be an object where keys are directive names (instead of an array as it is today)

**Comment by pkozlowski-opensource** [comment]
Updated output format so on the top-level we've got an object now instead of an array. Inputs and outputs are sorted now as well.

As an example here is output from running the script on our tabset:

```
{
    "NgbTabTitle": {
        "fileName": "src/tabset/tabset.ts",
        "className": "NgbTabTitle",
        "selector": "template[ngbTabTitle]",
        "description": "",
        "inputs": [],
        "outputs": []
    },
    "NgbTabContent": {
        "fileName": "src/tabset/tabset.ts",
        "className": "NgbTabContent",
        "selector": "template[ngbTabContent]",
        "description": "",
        "inputs": [],
        "outputs": []
    },
    "NgbTab": {
        "fileName": "src/tabset/tabset.ts",
        "className": "NgbTab",
        "selector": "ngb-tab",
        "description": "",
        "inputs": [{
            "name": "title",
            "type": "string",
            "description": ""
        }],
        "outputs": []
    },
    "NgbTabset": {
        "fileName": "src/tabset/tabset.ts",
        "className": "NgbTabset",
        "selector": "ngb-tabset",
        "description": "",
        "inputs": [{
            "name": "activeIdx",
            "defaultValue": "0",
            "description": ""
        }],
        "outputs": []
    }
}
```

**Comment by Foxandxss** [comment]
Lovely Pawel.

**Comment by icfantv** [comment]
Cool!

**Pull request closed without merging**
