### PR TITLE
style(all): re-format with clang 1.0.36

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Looks like clang 1.0.36 was released and it has impact on our code base.
Not sure how I feel about all the changes but hey, clang sets the rules here...

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
If clang keeps on doing those kind of things we might consider pinning a version we are using...

**Comment by Foxandxss** [comment]
I am completely against this change. One quote for HTML is horrible.

**Comment by pkozlowski-opensource** [comment]
> I am completely against this change. One quote for HTML is horrible.

Not to mention that it breaks our code.... The only alternative I can see is to pin to a previous version of clang... Sight...

**Comment by icfantv** [comment]
I think it's a good idea, in general, to pin versions until we have a chance to test the changed library in a controlled upgrade.  Otherwise, bugs significantly more subtle than a breaking build can creep in and we won't know it until someone reports it.  This has happened to us at work.

**Comment by pkozlowski-opensource** [comment]
> I think it's a good idea, in general, to pin versions until we have a chance to test the changed library in a controlled upgrade.

In this case we might consider shrink-wrapping our package.json. It is pain n a neck, but at least deals with the problem we are seeing here :-)

**Comment by icfantv** [comment]
I can't tell if you're agreeing with me or not.  :-)

**Pull request closed without merging**
