### PR TITLE
refactor(radio): minor style changes

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
@maxokorokov few changes that I've spotted only now... Could you PTAL?

### CODE REVIEW

**Comment by icfantv** [comment]
LTGM.  I'd love an explanation of what `@Host` was.

**Comment by pkozlowski-opensource** [comment]
> I'd love an explanation of what @Host was.

When looking for things to inject stop traversing injectors at the component (host view) boundary.

**Comment by maxokorokov** [comment]
Yeah, sure it looks good. I knew I was gonna forget something.
So why would you need to continue checking beyond the component level?

**Comment by pkozlowski-opensource** [comment]
> So why would you need to continue checking beyond the component level?

I could get back with the same question: "Why would you stop at a component level?" :-)
And since I like less code than more code...

**Comment by icfantv** [comment]
Cool.  got it.

**Comment by maxokorokov** [comment]
Yeah, I wrote the message above and thought that it looks like a useless "optimisation" in this case

**Comment by pkozlowski-opensource** [comment]
> useless "optimisation" in this case

Queries are auto-generated at compilation time so we are not getting any runtime optimization from restricting search scope (at least this is the theory :-))

**Pull request closed without merging**
