### PR TITLE
refactor(tests): move to inject from injectAsync

### PR DESCRIPTION
**Pull request by Foxandxss**
Bit of sugar added by Julie.

Not that it helps with clang tho ;(

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
I didn't follow the whole story too close but my very limited understanding is that now test can pass if we don't return a promise thus masking a failure:
* https://github.com/angular/angular/pull/5721
* https://github.com/angular/angular/issues/5515

Once again, I don't know all the details but we need to check that tests don't pass when they should fail. It might be unnecessary noise but I prefer to be safe than sorry.

**Comment by Foxandxss** [comment]
Oh, I wasn't aware of that. I am not reading angular issues / PRs.

**Comment by juliemr** [comment]
Details:

It is indeed possible for tests to fail if you don't return a promise. We've reintroduced `injectAsync` to attempt to give the developer more mental clues to guard against this. When it's supported by browsers we'll be able to catch those errors, but for now we're still recommending `injectAsync`.

For the record, you can always shoot yourself in the foot by accidentally using `inject` :(

```js
it('...', inject([], () => {
  service.doAsyncThing().then(() => {
    expect(2).toEqual(5); 
  });  // BAD: This will pass
}));

it('...', injectAsync([], () => {
 service.doAsyncThing().then(() => {
    expect(2).toEqual(5); 
  });  // GOOD: This will fail, since it will yell at you because you forgot to return a promise
}));

it('...', injectAsync([], () => {
  return service.doAsyncThing().then(() => {
    expect(2).toEqual(5); 
  });  // GOOD: This will fail, as it should
}));
```

**Comment by icfantv** [comment]
All that work @Foxandxss...sorry mate.  :-)

**Comment by wesleycho** [comment]
Any reason why we wouldn't just do `injectAsync(...)` and then inside do `return tcb.overrideTemplate()...` or whatever method used? It sounds like that would fix it.

**Comment by Foxandxss** [comment]
That is what we are doing now. I made this PR seeing @juliemr work on removing injectAsync, but there are other problems, so well, stuff happens :P

**Comment by wesleycho** [comment]
Ah I see, I missed the `return` deletion

**Comment by wesleycho** [comment]
Closing based on discussion

**Pull request closed without merging**
