### PR TITLE
refactor(accordion): organize code inside component

### PR DESCRIPTION
**Pull request by Foxandxss**
Another more.

If there is a constructor, always the first method (after inputs / outputs).

Input goes in alphabetical order, doesn't matter if they have setters or not. Hopefully we will get rid of setters anytime soon.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
I must say that I find it harder to read (that is, field declaration mixed with methods).
For now it is -1 from me, but open to be convinced

**Comment by Foxandxss** [comment]
So, should we do:

```typescript
class Foo {

  @Input() a;
  @Input() h;

  @Input()
  set b(...) { ... }

  get b() { ... }

  @Input()
  set r(...) { ... }

  get r() { ... }
```

AKA, all simple inputs first and then the setter / getters one. What about Outputs? before Input setters or after?

**Comment by wesleycho** [comment]
I think I agree with Pawel - having the simple declarations all together is easier to read since it doesn't require an extra line in between to separate it from the getters/setters.

**Comment by Foxandxss** [comment]
Updated it.

**Comment by wesleycho** [comment]
Now it looks like an extra line is added - this LGTM, although you should just merge it in if it's this trivial IMO.

**Comment by Foxandxss** [comment]
Yeah, I merge trivial for sure, but never realized that. I moved code around, made the PR, moved code around again and pushed back, but never looked into the diff.

**Pull request closed without merging**
