### PR TITLE
feat(dropdown): close on ESC keypress

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Not sure how to test it, at least not just yet :-)

Oh, and we need to have a conversation with clang format....

### CODE REVIEW

**Comment by Foxandxss** [comment]
How much fire to apply to clang format?

**Comment by Foxandxss** [comment]
Tried to test it with KeyboardEvent and dispatchEvent but is a no go.

**Comment by wesleycho** [comment]
Does ng2 not support keypress?

Also, I'm very unhappy with clang-format. How it indents the test files are no good.

**Comment by Foxandxss** [comment]
If tests are not doable, that is something else to issue at core, don't you think?

**Comment by wesleycho** [comment]
Any update on testability of this? If not, we could merge it and retroactively test it

**Comment by pkozlowski-opensource** [comment]
> Any update on testability of this?

Nope, didn't look into testing things that are triggered by keyboard events... 

> If not, we could merge it and retroactively test it

We could do this, but if anyone could give me a hand and dig into it, that would be awesome

**Comment by bekos** [comment]
Could `dispatchKeyEvent` function help? https://github.com/ng-lightning/ng-lightning/blob/master/test/helpers.ts#L11
You can call it like: `dispatchKeyEvent(el, 'Escape');`

**Comment by pkozlowski-opensource** [comment]
@bekos nice, thnx. I was hoping that we can have this kind of helper in the core, though. Will add it to my TODO list to discuss with Julie (or maybe it exists already?)

**Comment by pkozlowski-opensource** [comment]
@Foxandxss @wesleycho @bekos I think I've found a (simple) way to test those keyboard events, check the test in this PR. 

Could you please have a look so we can merge it? It was sitting around for wayyyy to long :-)

**Comment by Foxandxss** [comment]
Sounds good brother.

**Pull request closed without merging**
