### PR TITLE
fix(buttons): add  data-toggle='buttons' to radio group

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Spotted when working on buttons demo

cc.: @maxokorokov

### CODE REVIEW

**Comment by maxokorokov** [comment]
Yeah, I was using the markup from the [bs4 documentation](http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons) as a base, but this is good in case you forget it. Might also add the 'btn-group' style as well, though I don't know where to put the boundary on what we should auto-add.

**Comment by pkozlowski-opensource** [comment]
> Might also add the 'btn-group' style as well, though I don't know where to put the boundary on what we should auto-add. There is also the autocomplete=off in their examples on the input

Yeh, we could add those as well.  `btn-group` would be an easy fix. I will update the PR.

**Comment by pkozlowski-opensource** [comment]
@maxokorokov updated, PTAL

**Comment by maxokorokov** [comment]
Looks good!

**Pull request closed without merging**
