### PR TITLE
feat(dropdown): dropdown toggle

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
This is a proposal for dropdown toggle functionality. This is just to trigger discussion on the API so thus no tests.

**Comment by wesleycho** [comment]
I am fine with this, I'll leave it up to @Foxandxss if he has some other thoughts.

**Comment by Foxandxss** [comment]
LGTM when you add 300 tests for it :P

**Comment by pkozlowski-opensource** [comment]
> LGTM when you add 300 tests for it :P

Will do :-) Thnx for the review.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss @wesleycho added test, PTAL

**Pull request closed without merging**
