### PR TITLE
docs(README): fix link to TravisCI build

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**

### CODE REVIEW

**Comment by Foxandxss** [comment]
I don't get this one, it is working right now (I copied it from uibs).

**Comment by pkozlowski-opensource** [comment]
> it is working right now

Depends on what you mean by "working" :-) It is displaying a label but when you click on it it gets you to the SVG image - instead a link should point to the Travis build

**Comment by Foxandxss** [comment]
It is like those sticker that does nothing but they are pretty.

Will merge later.

**Comment by pkozlowski-opensource** [comment]
> It is like those sticker that does nothing but they are pretty.

Actually when you generate badge from TravisCI UI you are getting what I'm submitting in this PR

**Pull request closed without merging**
