### PR TITLE
chore(angular2): update to 2.0.0-rc.2

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
@maxokorokov I had to delete 2 tests while updating angular to 2.0.0-rc.2. Will open a separate issue for this so we can investigate.

### CODE REVIEW

**Comment by Foxandxss** [comment]
disable them with xit or comment them out, but don't delete them.

**Comment by pkozlowski-opensource** [comment]
Can't xit them since `gulp-ddescribe-iit` will complain....

**Comment by Foxandxss** [comment]
Riiight, then comment it out, is just to not forget about them.

**Comment by pkozlowski-opensource** [comment]
OK, commented out. TravisCI is green. Good to go?

**Comment by Foxandxss** [comment]
sure.

**Pull request closed without merging**
