### PR TITLE
refactor(pagination): add typings to tests

### PR DESCRIPTION
**Pull request by Foxandxss**
Fiddling a bit with `lib.d.ts` I figured out a better way of do typing on our elements. I think this is more idiomatic and works really good.

Also renamed `paginationCmpt` to `paginationCmp` to match the other business logic tests we have and also our test components. Also, less letters :P

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
I'm fine with typings, less fan of the variable rename. Maybe we should name it `ngbPagination`?

**Comment by Foxandxss** [comment]
Or perhaps `component` for all of them?

**Comment by wesleycho** [comment]
Just `ngbPagination` or `pagination` probably is better - they are instances of a class, and not a component in particular in those cases.

**Comment by Foxandxss** [comment]
I renamed it to `pagination`.

**Comment by pkozlowski-opensource** [comment]
LGTM

**Pull request closed without merging**
